


const Projects = [
    {
       Id:'1',
       pImg:'images/custom/jamies.png',
       ps1img:'images/custom/jamies.png',
       psub1img1:'images/custom/jamies2.png',
       psub1img2:'images/custom/jamies3.png',
       title:'Jamies Famous Burger',  
       subTitle:'Full Stack Development',  
       desc: 'This is an full stack application built using Laravel and react. Its for a restaurant that i made up. on the back end you can add employees in the system as well as add more food categories and items to the restaurant. Admin you can sales as well as other features that regular employees cant see.' ,
       tools: 'Photoshop, netlify, github',
       languages: 'css, laravel, html, js, php',
       datec: '29 April, 2021',
       category: 'Web',
       type: 'Fullstack',
       projectlink: 'http://jamies-restaurant.herokuapp.com/'
    },
    {
      Id:'2',
      pImg:'images/custom/fitness.png',
      ps1img:'images/custom/fitness.png',
      psub1img1:'images/custom/fitness2.png',
      psub1img2:'images/custom/fitness1.png',
      title:'Fitness',  
      subTitle:'Landing Page',  
      desc: 'This an example of a landing page for a fitness site. i coded this site using html css and bootstrap.' ,
      tools: 'Photoshop, netlify, github',
      languages: 'css, html',
      datec: '12 July, 2022',
      category: 'Web',
      type: 'Landing page',
      projectlink: 'https://dynamic-gaufre-6ef636.netlify.app/'
   },
   {
      Id:'3',
      pImg:'images/custom/lawncare.png',
      ps1img:'images/custom/lawncare.png',
      psub1img1:'images/custom/lawncare1.png',
      psub1img2:'images/custom/lawncare2.png',
      title:'Berries Lawn Care',  
      subTitle:'Landing Page',  
      desc: 'This is a landing page that i built using Laravel. This is only the landing page right now. in the future i will have a full stack site built out using this landing page. I built this site from scratch. ' ,
      tools: 'Photoshop, heroku, github',
      languages: 'css, laravel, html, js, php',
      datec: 'in progress',
      category: 'Web',
      type: 'Fullstack',
      projectlink: 'https://new-lawncare.herokuapp.com/'
   },
   {
      Id:'4',
      pImg:'images/custom/hair.png',
      ps1img:'images/custom/hair.png',
      psub1img1:'images/custom/hair1.png',
      psub1img2:'images/custom/hair2.png',
      title:'Hair Store Shopify Theme',  
      subTitle:'Shopify Theme',  
      desc: 'This is an shopify theme that i built off of the Debut theme. I designed and created all the inner sections of the website from scratch. Using bootstrap, htmml, & CSS. I also designed the banners and the collection images using canva so you can chnage and update them to say what ever you want to fit your site. The site is fully Responisive' ,
      tools: 'shopify, Canva',
      languages: 'css, liquid, html, js, php',
      datec: '19 June, 2021',
      category: 'Web',
      type: 'Shopify',
      projectlink: 'https://fmc-9.myshopify.com/',
      themepass: '123456'
   },
   {
      Id:'5',
      pImg:'images/custom/clothes.png',
      ps1img:'images/custom/clothes.png',
      psub1img1:'images/custom/clothes1.png',
      psub1img2:'images/custom/clothes2.png',
      title:'Shopify Theme',  
      subTitle:'Shopify Theme',  
      desc: 'This is an shopify theme that i built off of the Debut theme. I designed and created all the inner sections of the website from scratch. Using bootstrap, htmml, & CSS. I also designed the banners and the collection images using canva so you can chnage and update them to say what ever you want to fit your site. The site is fully Responisive' ,
      tools: 'shopify, Photoshop',
      languages: 'css, liquid, html, js, php',
      datec: '19 May, 2021',
      category: 'Web',
      type: 'Shopify',
      projectlink: 'https://fmc-5.myshopify.com/',
      themepass: '123456'
   },
   {
      Id:'6',
      pImg:'images/custom/spec.png',
      ps1img:'images/custom/1a.png',
      psub1img1:'images/custom/1b.png',
      psub1img2:'images/custom/1c.png',
      title:'Promotional Email',  
      subTitle:'Email Development',  
      desc: 'Before the email was just plain text, no images just text and links. So i offered to redo the email so that when customers open it it its more appealing and you may get more clicks. The color scheme is the same color scheme from his website so the brand and color schemes flows together. I added his logo and as well as a image. I coded everything in HTML and CSS and it is fully responsive.' ,
      tools: 'Litmus, Netlify, Photoshop',
      languages: 'css, html',
      datec: '25 Dec 2021',
      category: 'Web',
      type: 'Email',
      projectlink: 'https://stupefied-turing-9892ce.netlify.app/',
      themepass: 'N/A'
   },
   {
      Id:'7',
      pImg:'images/custom/fenty.png',
      ps1img:'images/custom/fenty.png',
      psub1img1:'images/custom/fenty1.png',
      psub1img2:'images/custom/fenty2.png',
      title:'Promotional Email',  
      subTitle:'Email Development',  
      desc: 'This is an example of a promotional email that i created. This email is created with HTML and CSS. This email is fully responsive and was tested using limtmus. It displays correctly across all major email clients. This email consist mainly of optimized images then at the bottom we have text.' ,
      tools: 'Litmus, Netlify, Photoshop',
      languages: 'css, html',
      datec: '25 Jan 2022',
      category: 'Web',
      type: 'Email',
      projectlink: 'https://musing-clarke-ae9222.netlify.app/',
      themepass: 'N/A'
   },
   {
      Id:'8',
      pImg:'images/custom/makartt.png',
      ps1img:'images/custom/makartt.png',
      psub1img1:'images/custom/2b.png',
      psub1img2:'images/custom/2c.png',
      title:'Transactional Email',  
      subTitle:'Email Development',  
      desc: 'This is an example of a Transactional email that i created. This email is created with HTML and CSS. This email is fully responsive and was tested using limtmus. It displays correctly across all major email clients. This email consist optimized images then at the bottom we have text.' ,
      tools: 'Litmus, Netlify, Photoshop',
      languages: 'css, html',
      datec: '25 Jan 2022',
      category: 'Web',
      type: 'Email',
      projectlink: 'https://hungry-euclid-5efafb.netlify.app/',
      themepass: 'N/A'
   },
   
   
    
]

export default Projects;